version: '2'
services:
    mysql:
        image: mysql:5.7
        env_file:
            - ./mysql.env
        volumes:
            - ./storage/mysql:/var/lib/mysql
        ports:
            - "3406:3306"

    web:
        build: ./
        container_name: web
        ports:
            - 8888:80
        volumes:
            - .:/var/www/public
            - ./storage/app:/var/www/storage/app
            - ./storage/logs:/var/www/storage/logs